apiVersion: v1
kind: Service
metadata:
  name: devopshift-web
  labels:
    app: devopshift-web
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: devopshift-web
  selector:
    app: devopshift-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopshift-web
  labels:
    app: devopshift-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopshift-web
  template:
    metadata:
      labels:
        app: devopshift-web
    spec:
      containers:
        - name: devopshift-web
          image: registry.ynot.work/skaffold/devopshift-web
          ports:
            - containerPort: 8080
