apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: registry.ynot.work/yanivomc/devopshift-fe
      context: ./devopshift-web/
    - image: registry.ynot.work/yanivomc/devopshift-be
      context: ./devopshift-app/
deploy:
  kubectl:
    manifests:
      - ./devopshift-web/kubernetes/*
      - ./devopshift-app/kubernetes/*
# portForward:
#   - resourceType: deployment
#     resourceName: devopshift-web
#     port: 8080
#     localPort: 9000
